# job-matrixのサンプル
name: demo-2_job-matrix

on:
  workflow_dispatch:

# それぞれの組み合わせで9Jobが並行で実行される
jobs:
  build-test:
    strategy:
      # マトリックスの値を定義(ここでは単なるラベル)
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        java: [ '8', '11', '17' ]
    runs-on: ${{ matrix.os }} # マトリックスが展開されたときの値が指定される
    name: ${{ matrix.os }} / Java ${{ matrix.java }} build-test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }} # マトリックスが展開されたときの値が指定される
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Build with Maven
      run: mvn -B clean --file pom.xml # とりあえずcleanだけ
